config/routes.rb
Rails.application.routes.draw do

  resources :tasks

put 'tasks/:id/done', to: "tasks#done", as: "done_task"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  before_validation :default_done, on: :create
  
  def default_done
    self.done = false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasks, only: [:show, :edit, :update, :destroy, :done]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def show
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def done
    p "je suis la!"
    @task.update_attributes(done: true)
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :content, :done)
  end

  def set_tasks
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Your tasks</h1>

<ul>
<% @tasks.each do |task| %>
<li>
  <%= link_to task.name, task_path(task) %> : <%= task.content %> (<%= task.done %>)
  <%= link_to "Delete", task_path(task),
  method: :delete,
  data: { confirm: "Are you sure?"} %>
  <%= link_to "Update", edit_task_path(task) %>
  <%= link_to "Done", done_task_path(task),
  method: :put %>
</li>
<% end %>
</ul>

<%= link_to "Create", new_task_path %>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<% if @task.done
  @done = "Oui" else @done = "Non" end %>

<h1>Your task</h1>
<h2>Name : <%= @task.name %></h2>
<p>Content <%= @task.content %></p>
<p>Done : <%= @done %></p>

<%= link_to "List of tasks", tasks_path %>